In [2]:
# from autonotebook import tqdm as notebook_tqdm
import torch
import numpy as np

In [55]:
x = torch.tensor(1.0,requires_grad=True)

In [56]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [57]:
y

tensor(12., grad_fn=<AddBackward0>)

In [58]:
y.backward()

In [59]:
x.grad

tensor(22.)

In [60]:
x

tensor(1., requires_grad=True)

In [61]:
x = torch.tensor([
    [1.,2.,3.],
    [3.,2.,1.]
],requires_grad = True)

In [64]:
y = 3*x+2

In [65]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [66]:
z = 2*y**2

In [67]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [71]:
out = z.mean()

In [72]:
out.backward()

In [73]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])

In [74]:
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)