In [2]:
import torch
import numpy as np

In [17]:
arr = np.array([1,2,3,4,5])

In [18]:
arr.dtype

dtype('int32')

In [26]:
x = torch.from_numpy(arr)

In [27]:
type(x)

torch.Tensor

In [28]:
type(arr)

numpy.ndarray

In [29]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [31]:
x.dtype

torch.int32

In [32]:
arr2d = np.arange(0.0,12.0)

In [38]:
arr2d = arr2d.reshape(4,3)

In [39]:
arr

array([1, 2, 3, 4, 5])

In [40]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [43]:
arr

array([99,  2,  3,  4,  5])

In [45]:
my_arr = np.arange(0,10)

In [46]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
my_tensor = torch.tensor(my_arr)

In [48]:
my_other_tensor = torch.from_numpy(my_arr)

In [49]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [50]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [52]:
my_arr[0] = 100

In [53]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [54]:
my_other_tensor

tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [55]:
my_arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [62]:
new_tensor = torch.IntTensor(arr)

In [63]:
new_tensor

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [69]:
torch.empty(4,2)

tensor([[1.6971e-07, 1.2812e-11],
        [6.7012e-10, 6.4103e-10],
        [2.6702e+23, 3.1987e+21],
        [1.6877e-07, 1.0675e-08]])

In [75]:
torch.arange(0,18,2).reshape(3,3).shape

torch.Size([3, 3])

In [92]:
torch.tensor([1,2])

tensor([1, 2])

In [96]:
x = torch.zeros(2,5)

In [100]:
torch.randn_like(x)

tensor([[-0.5868,  1.2196,  1.1830, -0.2522,  1.1457],
        [ 1.2376, -0.6941, -0.4134, -1.7430,  1.5466]])